name: Example workflow for Snyk Infrastructure as Code
on: push
permissions:
      id-token: write
      contents: read
      packages: read
jobs:
   snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master

      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: "bd232314-6d92-48dd-a7e8-1add00d92be0"
      - name: ls
        run: ls
        
      
        
      # Add a step to save the Snyk scan results in SARIF format
      - name: Save Snyk scan results as SARIF
        env:
           SNYK_TOKEN: "bd232314-6d92-48dd-a7e8-1add00d92be0"
        run: snyk iac test --all-projects > snyk.sarif.tmp && mv snyk.sarif.tmp snyk.sarif

      # Check if the SARIF file exists before uploading
      - name: Check SARIF file
        run: ls snyk.sarif
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
